In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC
import category_encoders as ce
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report



In [52]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [53]:
print(train_data.shape)
print(test_data.shape)
print(train_data.columns)
print(test_data.columns)

(1460, 81)
(1459, 80)
Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'Ga

In [54]:
train_data.head()


Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [55]:
print("La data tiene: ", train_data.shape[0], " filas y ", train_data.shape[1], " columnas")

La data tiene:  1460  filas y  81  columnas


In [56]:
print("La data tiene: ", test_data.shape[0], " filas y ", test_data.shape[1], " columnas")

La data tiene:  1459  filas y  80  columnas


In [57]:
print("La data tiene: ", test_data.shape[0], " filas y ", train_data.shape[1], " columnas")

La data tiene:  1459  filas y  81  columnas


In [58]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [59]:
missing_values = train_data.isnull().sum()
print(missing_values[missing_values > 0])

LotFrontage      259
Alley           1369
MasVnrType         8
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64


In [60]:
missing_values = test_data.isnull().sum()
print(missing_values[missing_values > 0])

MSZoning           4
LotFrontage      227
Alley           1352
Utilities          2
Exterior1st        1
Exterior2nd        1
MasVnrType        16
MasVnrArea        15
BsmtQual          44
BsmtCond          45
BsmtExposure      44
BsmtFinType1      42
BsmtFinSF1         1
BsmtFinType2      42
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
BsmtFullBath       2
BsmtHalfBath       2
KitchenQual        1
Functional         2
FireplaceQu      730
GarageType        76
GarageYrBlt       78
GarageFinish      78
GarageCars         1
GarageArea         1
GarageQual        78
GarageCond        78
PoolQC          1456
Fence           1169
MiscFeature     1408
SaleType           1
dtype: int64


In [61]:
missing_values = test_data.isnull().sum()
print(missing_values[missing_values > 0])

MSZoning           4
LotFrontage      227
Alley           1352
Utilities          2
Exterior1st        1
Exterior2nd        1
MasVnrType        16
MasVnrArea        15
BsmtQual          44
BsmtCond          45
BsmtExposure      44
BsmtFinType1      42
BsmtFinSF1         1
BsmtFinType2      42
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
BsmtFullBath       2
BsmtHalfBath       2
KitchenQual        1
Functional         2
FireplaceQu      730
GarageType        76
GarageYrBlt       78
GarageFinish      78
GarageCars         1
GarageArea         1
GarageQual        78
GarageCond        78
PoolQC          1456
Fence           1169
MiscFeature     1408
SaleType           1
dtype: int64


In [62]:
columns_to_fillna = [
    'Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 
    'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu', 
    'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 
    'PoolQC', 'Fence', 'MiscFeature'
]

train_data[columns_to_fillna] = train_data[columns_to_fillna].fillna(train_data[columns_to_fillna].mode().iloc[0])

In [63]:
columns_to_fillna = [
    'Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 
    'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu', 
    'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 
    'PoolQC', 'Fence', 'MiscFeature'
]

test_data[columns_to_fillna] = test_data[columns_to_fillna].fillna(test_data[columns_to_fillna].mode().iloc[0])

In [64]:
missing_values = train_data.isnull().sum()
print(missing_values[missing_values > 0])

LotFrontage    259
MasVnrArea       8
GarageYrBlt     81
dtype: int64


In [65]:
missing_values = test_data.isnull().sum()
print(missing_values[missing_values > 0])

MSZoning          4
LotFrontage     227
Utilities         2
Exterior1st       1
Exterior2nd       1
MasVnrArea       15
BsmtFinSF1        1
BsmtFinSF2        1
BsmtUnfSF         1
TotalBsmtSF       1
BsmtFullBath      2
BsmtHalfBath      2
KitchenQual       1
Functional        2
GarageYrBlt      78
GarageCars        1
GarageArea        1
SaleType          1
dtype: int64


In [66]:
columns_to_fillna = [ 'LotFrontage','MasVnrArea','GarageYrBlt'
]

train_data[columns_to_fillna] = train_data[columns_to_fillna].fillna(train_data[columns_to_fillna].mode().iloc[0])

In [67]:
columns_to_fillna = [ 'MSZoning','LotFrontage','Utilities','Exterior1st','Exterior2nd','MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','BsmtFullBath'
                     ,'BsmtHalfBath','KitchenQual','Functional','GarageYrBlt','GarageCars','GarageArea','SaleType'
]

test_data[columns_to_fillna] = test_data[columns_to_fillna].fillna(test_data[columns_to_fillna].mode().iloc[0])

In [68]:
missing_values = train_data.isnull().sum()
print(missing_values[missing_values > 0])

Series([], dtype: int64)


In [69]:
missing_values = test_data.isnull().sum()
print(missing_values[missing_values > 0])

Series([], dtype: int64)


In [70]:
train_data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave  Grvl      Reg   
1   2          20       RL         80.0     9600   Pave  Grvl      Reg   
2   3          60       RL         68.0    11250   Pave  Grvl      IR1   
3   4          70       RL         60.0     9550   Pave  Grvl      IR1   
4   5          60       RL         84.0    14260   Pave  Grvl      IR1   

  LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0         Lvl    AllPub  ...        0     Gd  MnPrv        Shed       0   
1         Lvl    AllPub  ...        0     Gd  MnPrv        Shed       0   
2         Lvl    AllPub  ...        0     Gd  MnPrv        Shed       0   
3         Lvl    AllPub  ...        0     Gd  MnPrv        Shed       0   
4         Lvl    AllPub  ...        0     Gd  MnPrv        Shed       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  
3      2   2006        WD        Abnorml     140000  
4     12   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [71]:
categorical_columns = train_data.select_dtypes(include=['object']).columns.tolist()

# Imprimir variables categóricas y sus valores distintos
for col in categorical_columns:
    unique_values = train_data[col].unique()
    print(f"Variable categórica: {col}")
    print(f"Valores distintos: {unique_values}")
    print("--------------------")

Variable categórica: MSZoning
Valores distintos: ['RL' 'RM' 'C (all)' 'FV' 'RH']
--------------------
Variable categórica: Street
Valores distintos: ['Pave' 'Grvl']
--------------------
Variable categórica: Alley
Valores distintos: ['Grvl' 'Pave']
--------------------
Variable categórica: LotShape
Valores distintos: ['Reg' 'IR1' 'IR2' 'IR3']
--------------------
Variable categórica: LandContour
Valores distintos: ['Lvl' 'Bnk' 'Low' 'HLS']
--------------------
Variable categórica: Utilities
Valores distintos: ['AllPub' 'NoSeWa']
--------------------
Variable categórica: LotConfig
Valores distintos: ['Inside' 'FR2' 'Corner' 'CulDSac' 'FR3']
--------------------
Variable categórica: LandSlope
Valores distintos: ['Gtl' 'Mod' 'Sev']
--------------------
Variable categórica: Neighborhood
Valores distintos: ['CollgCr' 'Veenker' 'Crawfor' 'NoRidge' 'Mitchel' 'Somerst' 'NWAmes'
 'OldTown' 'BrkSide' 'Sawyer' 'NridgHt' 'NAmes' 'SawyerW' 'IDOTRR'
 'MeadowV' 'Edwards' 'Timber' 'Gilbert' 'StoneBr' '

In [72]:
categorical_columns = test_data.select_dtypes(include=['object']).columns.tolist()

# Imprimir variables categóricas y sus valores distintos
for col in categorical_columns:
    unique_values = test_data[col].unique()
    print(f"Variable categórica: {col}")
    print(f"Valores distintos: {unique_values}")
    print("--------------------")

Variable categórica: MSZoning
Valores distintos: ['RH' 'RL' 'RM' 'FV' 'C (all)']
--------------------
Variable categórica: Street
Valores distintos: ['Pave' 'Grvl']
--------------------
Variable categórica: Alley
Valores distintos: ['Grvl' 'Pave']
--------------------
Variable categórica: LotShape
Valores distintos: ['Reg' 'IR1' 'IR2' 'IR3']
--------------------
Variable categórica: LandContour
Valores distintos: ['Lvl' 'HLS' 'Bnk' 'Low']
--------------------
Variable categórica: Utilities
Valores distintos: ['AllPub']
--------------------
Variable categórica: LotConfig
Valores distintos: ['Inside' 'Corner' 'FR2' 'CulDSac' 'FR3']
--------------------
Variable categórica: LandSlope
Valores distintos: ['Gtl' 'Mod' 'Sev']
--------------------
Variable categórica: Neighborhood
Valores distintos: ['NAmes' 'Gilbert' 'StoneBr' 'BrDale' 'NPkVill' 'NridgHt' 'Blmngtn'
 'NoRidge' 'Somerst' 'SawyerW' 'Sawyer' 'NWAmes' 'OldTown' 'BrkSide'
 'ClearCr' 'SWISU' 'Edwards' 'CollgCr' 'Crawfor' 'Blueste' '

In [75]:
categorical_columns = train_data.select_dtypes(include=['object']).columns.tolist()
encoder = ce.CountEncoder(cols=categorical_columns, min_group_size=100)
train_data_encoded = encoder.fit_transform(train_data)

In [78]:
categorical_columns = test_data.select_dtypes(include=['object']).columns.tolist()
encoder = ce.CountEncoder(cols=categorical_columns, min_group_size=100)
test_data_encoded = encoder.fit_transform(train_data)

In [76]:
train_data_encoded.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  LotShape  \
0   1          60      1151         65.0     8450    1454   1419       925   
1   2          20      1151         80.0     9600    1454   1419       925   
2   3          60      1151         68.0    11250    1454   1419       484   
3   4          70      1151         60.0     9550    1454   1419       484   
4   5          60      1151         84.0    14260    1454   1419       484   

   LandContour  Utilities  ...  PoolArea  PoolQC  Fence  MiscFeature  MiscVal  \
0         1311       1459  ...         0    1456   1336         1455        0   
1         1311       1459  ...         0    1456   1336         1455        0   
2         1311       1459  ...         0    1456   1336         1455        0   
3         1311       1459  ...         0    1456   1336         1455        0   
4         1311       1459  ...         0    1456   1336         1455        0   

   MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0       2    2008      1267           1198     208500  
1       5    2007      1267           1198     181500  
2       9    2008      1267           1198     223500  
3       2    2006      1267            101     140000  
4      12    2008      1267           1198     250000  

[5 rows x 81 columns]

In [79]:
test_data_encoded.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  LotShape  \
0   1          60      1151         65.0     8450    1454   1419       925   
1   2          20      1151         80.0     9600    1454   1419       925   
2   3          60      1151         68.0    11250    1454   1419       484   
3   4          70      1151         60.0     9550    1454   1419       484   
4   5          60      1151         84.0    14260    1454   1419       484   

   LandContour  Utilities  ...  PoolArea  PoolQC  Fence  MiscFeature  MiscVal  \
0         1311       1459  ...         0    1456   1336         1455        0   
1         1311       1459  ...         0    1456   1336         1455        0   
2         1311       1459  ...         0    1456   1336         1455        0   
3         1311       1459  ...         0    1456   1336         1455        0   
4         1311       1459  ...         0    1456   1336         1455        0   

   MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0       2    2008      1267           1198     208500  
1       5    2007      1267           1198     181500  
2       9    2008      1267           1198     223500  
3       2    2006      1267            101     140000  
4      12    2008      1267           1198     250000  

[5 rows x 81 columns]

In [80]:
X = train_data_encoded.drop('SalePrice', axis=1)
y = train_data_encoded['SalePrice']



In [81]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [84]:
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [85]:
svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train_scaled, y_train)

SVC(kernel='linear', random_state=42)

In [86]:
y_pred = svm_model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

C:\Users\manop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\manop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\manop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:14

In [87]:
print("Accuracy:", accuracy)

Accuracy: 0.00684931506849315


In [88]:
parameters = [
    {'C': 1, 'gamma': 0.1, 'degree': 2},
    {'C': 10, 'gamma': 0.01, 'degree': 3},
    {'C': 0.1, 'gamma': 0.01, 'degree': 4}
]


In [89]:
for param in parameters:
    svm_model_poly = SVC(kernel='poly', **param, random_state=42)
    svm_model_poly.fit(X_train_scaled , y_train)
    
    # Realizar predicciones en el conjunto de prueba
    y_pred = svm_model_poly.predict(X_test_scaled)
    
    # Evaluar el rendimiento del modelo
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)

C:\Users\manop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\manop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\manop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:14

In [90]:
print(f"Modelo SVM con parámetros: C={param['C']}, gamma={param['gamma']}, degree={param['degree']}")
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)
print("----------------------------------------------------")

Modelo SVM con parámetros: C=0.1, gamma=0.01, degree=4
Accuracy: 0.017123287671232876
Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
               precision    recall  f1-score   support

       35311       0.00      0.00      0.00         1
       40000       0.00      0.00      0.00         1
       55993       0.00      0.00      0.00         1
       60000       0.00      0.00      0.00         1
       64500       0.00      0.00      0.00         1
       66500       0.00      0.00      0.00         1
       67000       0.00      0.00      0.00         2
       68400       0.00      0.00      0.00         1
       68500       0.00      0.00      0.00         1
       75000       0.00      0.00      0.00         1
       75500       0.00      0.00      0.00         1
       79500       0.00      0.00      0.00         1
       81000       0.00      0.00      0.00     

In [111]:
kernels1 = ['rbf']

In [112]:
kernels2 = ['sigmoid']

In [113]:
for kernel_type in kernels1:
    svm_model = SVC(kernel=kernel_type, random_state=42)
    svm_model.fit(X_train_scaled, y_train)
    
    # Realizar predicciones en el conjunto de prueba
    y_pred = svm_model.predict(X_test_scaled)
    
    # Evaluar el rendimiento del modelo
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)

C:\Users\manop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\manop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\manop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classificati

In [114]:
print(f"Modelo SVM con kernel {kernel_type}")
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)
print("----------------------------------------------------")

Modelo SVM con kernel rbf
Accuracy: 0.003424657534246575
Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
               precision    recall  f1-score   support

       35311       0.00      0.00      0.00         1
       40000       0.00      0.00      0.00         1
       55993       0.00      0.00      0.00         1
       60000       0.00      0.00      0.00         1
       64500       0.00      0.00      0.00         1
       66500       0.00      0.00      0.00         1
       67000       0.00      0.00      0.00         2
       68400       0.00      0.00      0.00         1
       68500       0.00      0.00      0.00         1
       75000       0.00      0.00      0.00         1
       75500       0.00      0.00      0.00         1
       79500       0.00      0.00      0.00         1
       81000       0.00      0.00      0.00         1
       84500       0.00

In [115]:
for kernel_type2 in kernels2:
    svm_model = SVC(kernel=kernel_type2, random_state=42)
    svm_model.fit(X_train_scaled, y_train)
    
    # Realizar predicciones en el conjunto de prueba
    y_pred = svm_model.predict(X_test_scaled)
    
    # Evaluar el rendimiento del modelo
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)

C:\Users\manop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\manop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\manop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classificati

In [116]:
print(f"Modelo SVM con kernel {kernel_type2}")
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)
print("----------------------------------------------------")

Modelo SVM con kernel sigmoid
Accuracy: 0.017123287671232876
Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
               precision    recall  f1-score   support

       35311       0.00      0.00      0.00         1
       40000       0.00      0.00      0.00         1
       55993       0.00      0.00      0.00         1
       60000       0.00      0.00      0.00         1
       64500       0.00      0.00      0.00         1
       66500       0.00      0.00      0.00         1
       67000       0.00      0.00      0.00         2
       68400       0.00      0.00      0.00         1
       68500       0.00      0.00      0.00         1
       75000       0.00      0.00      0.00         1
       75500       0.00      0.00      0.00         1
       79500       0.00      0.00      0.00         1
       81000       0.00      0.00      0.00         1
       84500       